[features]
seeds = false
[programs.devnet]
arc = "8u3q7KUBALJgKLpmxA94RNkuYxfmrw9C9oiM1Dtb8yNd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/luke/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
